{
 "title": "OPCUA - Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Motores Ligados",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\n\nfrom(bucket: \"opc\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"opcua\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /motor\\d+Status/)\n  |> filter(fn: (r) => r[\"host\"] == \"f0eee15fd0b8\")\n  |> map(fn: (r) => ({ r with _field: strings.title(v: strings.replace(i: 1, v: r._field, t: \"Status\", u: \"\")), _value: if r._value == \"on\" then \"1\" else if r._value == \"off\" then \"0\" else \"0\" }))\n  |> toInt()\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n\n"
    }
   ]
  },
  {
   "title": "Velocidade (RPM)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\n\nfrom(bucket: \"opc\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"opcua\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /(?i)motor\\d+Speed/)\n  |> filter(fn: (r) => r[\"host\"] == \"f0eee15fd0b8\")\n  |> map(fn: (r) => ({ r with _field: strings.toTitle(v: strings.replace(i: 1, v: r._field, t: \"(?i)Speed\", u: \"\")), _value: r._value * 60.00/6.3 }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Tensão de Armadura (V)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 13, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\n\nfrom(bucket: \"opc\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"opcua\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /motor\\d+Voltage/)\n  |> filter(fn: (r) => r[\"host\"] == \"f0eee15fd0b8\")\n  |> map(fn: (r) => ({ r with _field: strings.toTitle(v: strings.replace(i:1,v: r._field, t: \"Speed\", u: \"\")), _value: r._value }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Tensão de Armadura",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"opc\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"opcua\")\n  |> filter(fn: (r) => r[\"id\"] == \"motor3\" or r[\"id\"] == \"motor4\" or r[\"id\"] == \"motor5\" or r[\"id\"] == \"motor6\" or r[\"id\"] == \"motor7\" or r[\"id\"] == \"motor8\" or r[\"id\"] == \"motor9\" or r[\"id\"] == \"motor11\" or r[\"id\"] == \"motor2\" or r[\"id\"] == \"motor10\" or r[\"id\"] == \"motor1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"motor2Voltage\" or r[\"_field\"] == \"motor3Voltage\" or r[\"_field\"] == \"motor5Voltage\" or r[\"_field\"] == \"motor4Voltage\" or r[\"_field\"] == \"motor6Voltage\" or r[\"_field\"] == \"motor7Voltage\" or r[\"_field\"] == \"motor8Voltage\" or r[\"_field\"] == \"motor9Voltage\" or r[\"_field\"] == \"motor1Voltage\" or r[\"_field\"] == \"motor10Voltage\")\n  |> filter(fn: (r) => r[\"host\"] == \"f0eee15fd0b8\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Motor Velocidade",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 8, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"opc\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"opcua\")\n  |> filter(fn: (r) => r[\"id\"] == \"motor3\" or r[\"id\"] == \"motor4\" or r[\"id\"] == \"motor5\" or r[\"id\"] == \"motor6\" or r[\"id\"] == \"motor7\" or r[\"id\"] == \"motor8\" or r[\"id\"] == \"motor9\" or r[\"id\"] == \"motor11\" or r[\"id\"] == \"motor2\" or r[\"id\"] == \"motor10\" or r[\"id\"] == \"motor1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"motor2Speed\" or r[\"_field\"] == \"motor3Speed\" or r[\"_field\"] == \"motor5Speed\" or r[\"_field\"] == \"motor4Speed\" or r[\"_field\"] == \"motor6Speed\" or r[\"_field\"] == \"motor7Speed\" or r[\"_field\"] == \"motor8Speed\" or r[\"_field\"] == \"motor9Speed\" or r[\"_field\"] == \"motor1Speed\" or r[\"_field\"] == \"motor10Speed\")\n  |> filter(fn: (r) => r[\"host\"] == \"f0eee15fd0b8\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}